name: Destroy clevercloud application

on:
  workflow_call:
    inputs:
      application-alias:
        required: true
        type: string
      deployment-owner-type:
        required: true
        type: string

jobs:
  destroy-deployed-application:
    runs-on: ubuntu-latest
    container:
      image: clevercloud/clever-tools
      env:
        CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
        CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
    steps:
      - name: Link the application (ORGANISATION)
        if: ${{ inputs.deployment-owner-type == 'organisation' }}
        run: clever link ${{ inputs.application-alias }} --org ${{ secrets.CLEVER_ORG_ID }}

      - name: Link the application (PERSONAL USE)
        if: ${{ inputs.deployment-owner-type == 'personal' }}
        run: clever link ${{ inputs.application-alias }}

      - name: Delete the deployed application
        run: clever delete --alias ${{ inputs.application-alias }} --yes
