name: Cron - Start demo environments according to team schedule
# Every morning around 8:00 GMT

on:
  workflow_dispatch:
#  schedule:
#    #Monday through Friday around 7:00 UTC (not using exact hours helps with runners availability)
#    - cron: '58 6 * * 1,2,3,4,5'

env:
  application-name: 'my-app'
  # Should be either 'personal' or 'organisation'
  deployment-owner-type: 'personal'

jobs:
  enumerate-feature-branches:
    uses: ./.github/workflows/_enumerate-feature-branches.reusable.yml

  start-target-applications:
    needs:
      - enumerate-feature-branches
    runs-on: ubuntu-latest
    container:
      image: clevercloud/clever-tools
      env:
        CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
        CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
    strategy:
      matrix:
        value: ${{ fromJSON(needs.enumerate-feature-branches.outputs.branches) }}
    steps:
      - name: Link and start a clevercloud demo application (ORGANISATION)
        if: ${{ inputs.deployment-owner-type == 'organisation' }}
        continue-on-error: true
        run: |
          clever link ${{ format('{0}-{1}', env.application-name, matrix.value) }} --org ${{ secrets.CLEVER_ORG_ID }}
          clever restart

      - name: Link and start a clevercloud demo application (PERSONAL USE)
        if: ${{ inputs.deployment-owner-type == 'personal' }}
        continue-on-error: true
        run: |
          clever link ${{ format('{0}-{1}', env.application-name, matrix.value) }}
          clever restart
