name: Cron - Stop demo environments according to team schedule
# every day around 7pm UTC (8pm GMT)

on:
  workflow_dispatch:
#  schedule:
#    #Monday through Friday around 19:00 UTC (not using exact hours helps with runners availability)
#    - cron: '58 18 * * 1,2,3,4,5'

env:
  application-name: 'my-app'
  # Should be either 'personal' or 'organisation'
  deployment-owner-type: 'personal'

jobs:
  enumerate-feature-branches:
    uses: ./.github/workflows/_enumerate-feature-branches.reusable.yml

  stop-target-applications:
    needs:
      - enumerate-feature-branches
    runs-on: ubuntu-latest
    container:
      image: clevercloud/clever-tools
      env:
        CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
        CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
    strategy:
      matrix:
        value: ${{ fromJSON(needs.enumerate-feature-branches.outputs.targets-branches) }}
    steps:
      - name: Link and stop a clevercloud demo application (ORGANISATION)
        if: ${{ inputs.deployment-owner-type == 'organisation' }}
        continue-on-error: true
        run: |
          clever link ${{ format('{0}-{1}', env.application-name, matrix.value) }} --org ${{ secrets.CLEVER_ORG_ID }}
          clever stop

      - name: Link and stop a clevercloud demo application (PERSONAL USE)
        if: ${{ inputs.deployment-owner-type == 'personal' }}
        continue-on-error: true
        run: |
          clever link ${{ format('{0}-{1}', env.application-name, matrix.value) }}
          clever stop

  destroy-deployed-application:
    runs-on: ubuntu-latest
    container:
      image: rcambonie/scalingo-cli
    strategy:
      matrix:
        value: ${{ fromJSON(needs.enumerate-feature-branches.outputs.targets-branches) }}
    steps:
      - name: Login with api-token
        run: scalingo login --api-token=${{ secrets.SCALINGO_API_TOKEN }}

      - name: Destroy the application if it exist
        id: delete-app
        continue-on-error: true
        run: |
          APP_NAME=$(echo ${{ matrix.value }} | cut -d'/' -f 2)
          set +e
          APP_EXIST=$(scalingo apps | grep -c APP_NAME)
          set -e
          if [[ $APP_EXIST -eq 1 ]]; then (echo APP_NAME | scalingo -a APP_NAME destroy); else echo 'App not found'; fi