name: zReusable Scalingo Postgresql Addon Setup

on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string

      addon-plan-postgresql:
        required: true
        type: string

    secrets:
      SCALINGO_API_TOKEN:
        required: true

jobs:
  addon-postgresql-with-extentions:
    name: Add the postgresql addon if not present
    runs-on: ubuntu-latest
    container:
      image: rcambonie/scalingo-cli

    steps:
      - name: Login with api-token
        run: scalingo login --api-token=${{ secrets.SCALINGO_API_TOKEN }}

      - name: check if addon exists
        id: postgresql-addon-exist
        run: |
          set +e
          POSTGRESQL_ADDON_EXIST=$(scalingo --app ${{ inputs.application-name }} addons | grep -c PostgreSQL)
          set -e
          echo "::set-output name=postgresql-addon-exist::$POSTGRESQL_ADDON_EXIST"

      - name: Add the postgresql addon
        id: postgresql-addon-add
        if: steps.postgresql-addon-exist.outputs.postgresql-addon-exist == 0
        run: |
          scalingo --app ${{ inputs.application-name }} addons-add postgresql ${{ inputs.addon-plan-postgresql }}
