name: zReusable - Add AWS credentials to workspace

on:
  workflow_call:
    inputs:
      workspace-name:
        required: true
        type: string
      organisation-name:
        required: true
        type: string
    secrets:
      TF_API_TOKEN:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  get-workspace-id:
    uses: romain-cambonie/serenity-workflow-dev/.github/workflows/_get-workspace-id.terraform.reusable.yml@master
    with:
      organisation-name: ${{ inputs.organisation-name }}
      workspace-name: ${{ inputs.workspace-name }}
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  json-payloads:
    runs-on: ubuntu-latest
    outputs:
      aws-access-key-id-payload: ${{ steps.aws-access-key-id-payload.outputs.payload }}
      aws-secret-access-key-payload: ${{ steps.aws-secret-access-key-payload.outputs.payload }}

    steps:
      - name: Generate aws access key id payload
        id: aws-access-key-id-payload
        run: >-
          AWS_ACCESS_KEY_ID_JSON_PAYLOAD=$(
          jq
          '{
            type: "vars",
              attributes: {
                key: "AWS_ACCESS_KEY_ID",
                value: ${{ secrets.AWS_ACCESS_KEY_ID }},
                description:"Aws access key id",
                category:"env",
                hcl:false,
                sensitive: true
              }
          }' | 
          sed 's/ //g'
          )
          
          echo "::set-output name=payload::$AWS_ACCESS_KEY_ID_JSON_PAYLOAD"

      - name: Generate aws secret access key payload
        id: aws-secret-access-key-payload
        run: >-
          AWS_SECRET_ACCESS_KEY_JSON_PAYLOAD=$(
          jq
          '{
            type: "vars",
              attributes: {
                key: "AWS_SECRET_ACCESS_KEY",
                value: ${{ secrets.AWS_SECRET_ACCESS_KEY }},
                description:"Aws access key secret",
                category:"env",
                hcl:false,
                sensitive: true
              }
          }' | 
          sed 's/ //g'
          )

          echo "::set-output name=payload::$AWS_SECRET_ACCESS_KEY_JSON_PAYLOAD"

  set-key-id:
    needs:
      - get-workspace-id
      - json-payloads
    uses: romain-cambonie/serenity-workflow-dev/.github/workflows/_set-workspace-variable.terraform.reusable.yml@master
    with:
      workspace-id: ${{ needs.get-workspace-id.outputs.workspace-id }}
      payload-as-json-string: ${{ needs.json-payloads.outputs.aws-access-key-id-payload }}
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  set-key-secret:
    needs:
      - get-workspace-id
      - json-payloads
    uses: romain-cambonie/serenity-workflow-dev/.github/workflows/_set-workspace-variable.terraform.reusable.yml@master
    with:
      workspace-id: ${{ needs.get-workspace-id.outputs.workspace-id }}
      payload-as-json-string: ${{ needs.json-payloads.outputs.aws-secret-access-key-payload }}
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}