# Abstract
# Create sequentially the given extentions on the application linked postgresql addon

# extentions-as-comma-separated-string input example: 'lint,prettier:check,test:unit'

name: zReusable Create Postgresql Matrix Workflow On Scalingo

on:
  workflow_call:
    inputs:
      extentions-as-comma-separated-string:
        required: true
        type: string
      application-name:
        required: true
        type: string

    secrets:
      SCALINGO_API_TOKEN:
        required: true

jobs:
  get-extentions:
    uses: romain-cambonie/serenity-workflow-dev/.github/workflows/_matrix-from-string.reusable.yml@master
    with:
      input-string: ${{ inputs.extentions-as-comma-separated-string }}
      separator: ','
      field: 'extention'

  create-extention:
    name: ' '
    runs-on: ubuntu-latest
    needs:
      - get-extentions
    strategy:
      fail-fast: true
      # Max parallel 1 assure we will run jobs sequencially
      max-parallel: 1
      matrix:
        extention: ${{ fromJSON(needs.get-extentions.outputs.matrix) }}

    steps:
      - name: Login with api-token
        run: scalingo login --api-token=${{ secrets.SCALINGO_API_TOKEN }}

      - name: ${{matrix.extention}}
        env:
          EXTENTION: ${{matrix.extention}}
        run: echo 'CREATE extension $EXTENTION; \q' | scalingo --app ${{ inputs.application-name }} pgsql-console
