name: zReusable - Get database connexion info from scalingo env var

on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string

    secrets:
      SCALINGO_API_TOKEN:
        required: true
      GPG_SECRET_SIGNING_PASSPHRASE:
        required: true

    outputs:
      db:
        description: 'Database name'
        value: ${{ jobs.set-encrypted-outputs.outputs.dburl }}

jobs:
    # Copy of _get-workspace-id.terraform.reusable.yml, using raw for call depth issues
    set-encrypted-outputs:
      name: Extract the database-user (same value) identifier
      runs-on: ubuntu-latest
      container:
        image: rcambonie/scalingo-cli

      outputs:
        dburl: ${{ steps.dburl.outputs.dburl }}

      steps:
        - name: Login with api-token
          run: scalingo login --api-token=${{ secrets.SCALINGO_API_TOKEN }}

        - name: Extract user-database and database name from connexion string
          id: dburl
          run: |
            TARGET_DATABASE_URL=$(scalingo --app ${{ inputs.application-name }} env | grep SCALINGO_POSTGRESQL_URL=)
            TARGET_DATABASE_URL=${TARGET_DATABASE_URL//SCALINGO_POSTGRESQL_URL/}
            echo "::set-output name=dburl::$TARGET_DATABASE_URL"