name: zReusable Grant all privilege on all tables in public schema

on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string
      user-database:
        required: true
        type: string

    secrets:
      SCALINGO_API_TOKEN:
        required: true

jobs:
  grant-privileges:
    runs-on: ubuntu-latest
    container:
      image: rcambonie/scalingo-cli

    steps:
      - name: Login with api-token
        run: scalingo login --api-token=${{ secrets.SCALINGO_API_TOKEN }}

      - name: Grant privileges
        run: >-
          echo "GRANT CREATE ON SCHEMA public TO ${{ inputs.user-database }};
          GRANT ALL PRIVILEGES ON DATABASE ${{ inputs.user-database }} TO ${{ inputs.user-database }};
          GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${{ inputs.user-database }};
          GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${{ inputs.user-database }};
          ALTER DEFAULT PRIVILEGES FOR USER ${{ inputs.user-database }} IN SCHEMA public GRANT ALL ON TABLES TO ${{ inputs.user-database }};
          ALTER DEFAULT PRIVILEGES FOR USER ${{ inputs.user-database }} IN SCHEMA public GRANT ALL ON SEQUENCES TO ${{ inputs.user-database }};
          \q" 
          | scalingo --app ${{ inputs.application-name }} pgsql-console
