# Payload example (as json)
# {
#    "type":"vars",
#    "attributes": {
#      "key":"some_key",
#      "value":"some_value",
#      "description":"some description",
#      "category":"terraform",
#      "hcl":false,
#      "sensitive":false
#    }
# }
#

name: Reusable Terraform set workspace variable

on:
  workflow_call:
    inputs:
      workspace-id:
        required: true
        type: string
      payload-as-json-string:
        required: true
        type: string
      terraform-workspace-variables-api-endpoint:
        required: false
        type: string
        default: 'https://app.terraform.io/api/v2/workspaces/'

    secrets:
      TF_API_TOKEN:
        required: true

jobs:
  set-workspace-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Execute api request
        run: |
          curl \
          --header "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
          --header "Content-Type: application/vnd.api+json" \
          --request POST \
          --data ${{ inputs.payload-as-json-string }} \
          ${{ inputs.terraform-workspace-variables-api-endpoint }}${{ inputs.workspace-id }}/vars
