name: zReusable - Create a ready to use workspace with AWS credentials

on:
  workflow_call:
    inputs:
      workspace-name-with-prefix:
        required: true
        type: string
      organisation-name:
        required: true
        type: string
      terraform-api-organizations-endpoint:
        required: false
        type: string
        default: 'https://app.terraform.io/api/v2/organizations/'
      terraform-workspace-api-endpoint:
        required: false
        type: string
        default: 'https://app.terraform.io/api/v2/workspaces/'

    secrets:
      TF_API_TOKEN:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      GPG_SECRET_SIGNING_PASSPHRASE:
        required: true

jobs:
  workspace-already-exist:
    uses: romain-cambonie/serenity-workflow-dev/.github/workflows/_workspace-already-exist.terraform.reusable.yml@master
    with:
      organisation-name: ${{ inputs.organisation-name }}
      workspace-name-with-prefix: ${{ inputs.workspace-name-with-prefix }}
      terraform-api-organizations-endpoint: ${{ inputs.terraform-api-organizations-endpoint }}
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  create-workspace:
    needs:
      - workspace-already-exist
    if: needs.workspace-already-exist.outputs.status == 'false'
    uses: romain-cambonie/serenity-workflow-dev/.github/workflows/_create-workspace.terraform.reusable.yml@master
    with:
      organisation-name: ${{ inputs.organisation-name }}
      workspace-name-with-prefix: ${{ inputs.workspace-name-with-prefix }}
      terraform-api-organizations-endpoint: ${{ inputs.terraform-api-organizations-endpoint }}
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  add-aws-credentials-to-workspace:
    needs:
      - create-workspace
    if: needs.workspace-already-exist.outputs.status == 'false'
    uses: romain-cambonie/serenity-workflow-dev/.github/workflows/_add-aws-credentials-to-workspace.terraform.reusable.yml@master
    with:
      organisation-name: ${{ inputs.organisation-name }}
      workspace-name-with-prefix: ${{ inputs.workspace-name-with-prefix }}
      terraform-api-organizations-endpoint: ${{ inputs.terraform-api-organizations-endpoint }}
      terraform-workspace-api-endpoint: ${{ inputs.terraform-workspace-api-endpoint }}
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GPG_SECRET_SIGNING_PASSPHRASE: ${{ secrets.GPG_SECRET_SIGNING_PASSPHRASE }}