# THIS DOES NOT WORK YET !
# This is a Work In Progress
name: Check periodically if addon has the target status

on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string
      addon-name:
        required: true
        type: string
      status:
        required: true
        type: string
      interval:
        required: true
        type: number
      attempts:
        required: true
        type: number

    secrets:
      SCALINGO_API_TOKEN:
        required: true

    outputs:
      status-reached:
        description: "'true' if status is reached, 'false' otherwise"
        value: ${{ jobs.addon-status-check.outputs.status-reached }}

jobs:
  addon-status-check:
    name: Check if the addons is in the target status
    runs-on: ubuntu-latest
    container:
      image: rcambonie/scalingo-cli

    outputs:
      status-reached: ${{ steps.check-status.outputs.status-reached  }}

    steps:
      - name: Login with api-token
        run: scalingo login --api-token=${{ secrets.SCALINGO_API_TOKEN }}

      - name: Check if the addon is running
        id: check-status
        run: >-
          for i in {0..${{ inputs.attempts }}};
          
          do
          
          if (( $(scalingo -a ${{ inputs.application-name }} addons | grep -c '${{ inputs.addon-name }}.*${{ inputs.status }}' ) == 1 ));
          then echo "success" ; echo "::set-output name=status-reached::'true'"; exit 0; 
          fi;
          
          echo "waiting"; sleep ${{ inputs.interval }};
          
          done
          
          echo "::set-output name=status-reached::'false'"
          
          exit 1
