name: Reusable Terraform get if workspace exist

on:
  workflow_call:
    inputs:
      organisation-name:
        required: true
        type: string
      workspace-name-with-prefix:
        required: true
        type: string
      terraform-api-organizations-endpoint:
        required: false
        type: string
        default: 'https://app.terraform.io/api/v2/organizations/'

    secrets:
      TF_API_TOKEN:
        required: true

    outputs:
      status:
        description: "'true' if workspace with the same name exist 'false' otherwise"
        value: ${{ jobs.workspace-already-exist.outputs.status }}

jobs:
  workspace-already-exist:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.workspace-already-exist.outputs.status }}

    steps:
      - name: Exist if a name matches the given name
        id: workspace-already-exist
        run: >-
          set +e
          
          curl 
          --header "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" 
          --header "Content-Type: application/vnd.api+json" 
          --request GET 
          ${{ inputs.terraform-api-organizations-endpoint }}${{ inputs.organisation-name }}/workspaces 
          |
          jq '.data | .[] | select(.attributes.name == "${{workspace-name-with-prefix}}") | length'
          
          set -e
          
          if [[ $? -eq 1 ]]; then EXIST='true'; else EXIST='false'; fi
          
          echo "::set-output name=status::$EXIST"
