# This is a Work In Progress
name: Replicate db

on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string
      addon-plan-postgresql:
        required: true
        type: string
    secrets:
      SCALINGO_API_TOKEN:
        required: true

jobs:
  create-application-on-scalingo:
    uses: romain-cambonie/serenity-workflows/.github/workflows/_prepare-application-and-keys.scalingo.reusable.yml@master
    with:
      application-name: ${{ inputs.application-name }}
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}

  setup-database-addon:
    needs:
      - create-application-on-scalingo
    uses: romain-cambonie/serenity-workflows/.github/workflows/_setup-addon.postgresql.scalingo.reusable.yml@master
    with:
      application-name: ${{ inputs.application-name }}
      addon-plan-postgresql: ${{ inputs.addon-plan-postgresql }}
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}


#  migrate-database:
#    needs:
#      - dynamic-variables
#      - setup-database-addon
#    uses: ./.github/workflows/_migrate.postgresql.scalingo.reusable.yml
#    with:
#      application-name: ${{ needs.dynamic-variables.outputs.application-name }}
#      migration-dependencies: "node-pg-migrate pg-format date-fns fs-extra ramda zod"
#    secrets:
#      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
#
#  clone-immersion-pe-db-data:
#    needs:
#      - dynamic-variables
#      - migrate-database
#    uses: ./.github/workflows/_dump-restore-remote-data.postgresql.scalingo.reusable.yml
#    with:
#      application-name: ${{ needs.dynamic-variables.outputs.application-name }}
#    secrets:
#      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
#      REMOTE_DATABASE_URL: ${{ secrets.PE_PRODUCTION_DATABASE_URL }}
#
#  notify-discord:
#    if: ${{ needs.dynamic-variables.outputs.is-discord-hooked == 'true' }}
#    needs:
#      - dynamic-variables
#      - clone-immersion-pe-db
#    uses: ./.github/workflows/_notify-deployment.discord.reusable.yml
#    with:
#      deployer-name: "Scalingo Back Deployer"
#      application-name: ${{ needs.dynamic-variables.outputs.application-name }}
#      deployed-domain: ${{ needs.dynamic-variables.outputs.deployed-domain }}
#    secrets:
#      DISCORD_NOTIFY_HOOK_URL: ${{ secrets.DISCORD_NOTIFY_HOOK_URL }}
