# This is a Work In Progress
# Example usage
# my-replication-job:
#   uses: romain-cambonie/serenity-workflows/.github/workflows/replicate-db.use-case.yml@master
#   with:
#     application-name: 'my-app'
#     addon-plan-postgresql: 'postgresql-starter-1024'
#     extensions: 'postgis,hstore'
#   secrets:
#     SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}

name: Replicate db

on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string
      addon-plan-postgresql:
        required: true
        type: string
      extensions:
        required: true
        type: string
    secrets:
      SCALINGO_API_TOKEN:
        required: true
      REMOTE_DATABASE_URL:
        required: true

jobs:
  create-application-on-scalingo:
    uses: romain-cambonie/serenity-workflows/.github/workflows/_prepare-application-and-keys.scalingo.reusable.yml@master
    with:
      application-name: ${{ inputs.application-name }}
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}

  setup-database-addon:
    needs:
      - create-application-on-scalingo
    uses: romain-cambonie/serenity-workflows/.github/workflows/_setup-addon.postgresql.scalingo.reusable.yml@master
    with:
      application-name: ${{ inputs.application-name }}
      addon-plan-postgresql: ${{ inputs.addon-plan-postgresql }}
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}

  # TODO This is very ugly, find better solution
  wait-for-addon:
    needs:
      - setup-database-addon
    runs-on: ubuntu-latest
    steps:
      - name: Wait for postgresql addon to be available
        run: sleep 45

  install-postgresql-extensions:
    needs:
      - setup-database-addon
      - wait-for-addon
    # TODO Change target workflow to
    # romain-cambonie/serenity-workflows/.github/workflows/_create-extension.postgresql.scalingo.reusable.yml@master
    # when ready
    uses: romain-cambonie/serenity-workflow-dev/.github/workflows/_create-extension.postgresql.scalingo.reusable.yml@master
    with:
      extensions-as-comma-separated-string: ${{ inputs.extensions }}
      application-name: ${{ inputs.application-name }}
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}

  replicate-remote-db:
    needs:
      - dynamic-variables
      - install-postgresql-extensions
    uses: ./.github/workflows/_replicate-db.postgresql.scalingo.reusable.yml
    with:
      application-name: ${{ needs.dynamic-variables.outputs.application-name }}
    secrets:
      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
      REMOTE_DATABASE_URL: ${{ secrets.REMOTE_DATABASE_URL }}

#  migrate-database:
#    needs:
#      - dynamic-variables
#      - setup-database-addon
#    uses: ./.github/workflows/_migrate.postgresql.scalingo.reusable.yml
#    with:
#      application-name: ${{ needs.dynamic-variables.outputs.application-name }}
#      migration-dependencies: "node-pg-migrate pg-format date-fns fs-extra ramda zod"
#    secrets:
#      SCALINGO_API_TOKEN: ${{ secrets.SCALINGO_API_TOKEN }}
#

#  notify-discord:
#    if: ${{ needs.dynamic-variables.outputs.is-discord-hooked == 'true' }}
#    needs:
#      - dynamic-variables
#      - clone-immersion-pe-db
#    uses: ./.github/workflows/_notify-deployment.discord.reusable.yml
#    with:
#      deployer-name: "Scalingo Back Deployer"
#      application-name: ${{ needs.dynamic-variables.outputs.application-name }}
#      deployed-domain: ${{ needs.dynamic-variables.outputs.deployed-domain }}
#    secrets:
#      DISCORD_NOTIFY_HOOK_URL: ${{ secrets.DISCORD_NOTIFY_HOOK_URL }}
